/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package countdowntimer;

/**
 *
 * @author raymondli
 */
import java.awt.Color;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import java.io.IOException;


public class TimerSwing extends javax.swing.JFrame {

    /**
     * Creates new form TimerSwing
     */
    int min, sec, min1, sec1;
    Timer timer;
    boolean ifStop = false;
    
    public TimerSwing() {
        initComponents();
        for(int i = 0; i < 24; i++){
            if(i < 10){
                cboxMin.addItem(String.valueOf("0" + i));
            }
            else{
                cboxMin.addItem(String.valueOf(i));
            }
            
        }
        
        //Populate Sec ComboBox
        for(int i = 0; i < 60; i++){
            if(i < 10){
                cboxSec.addItem(String.valueOf("0" + i));
            }
            else{
                cboxSec.addItem(String.valueOf(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxMin = new javax.swing.JComboBox<>();
        cboxSec = new javax.swing.JComboBox<>();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Count Down Timer");

        lblMin.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        lblMin.setText("00");

        lblSec.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        lblSec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSec.setText("00");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");

        cboxMin.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        cboxMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxMinActionPerformed(evt);
            }
        });

        cboxSec.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        cboxSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxSecActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStart)
                            .addComponent(lblMin)
                            .addComponent(cboxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSec)
                            .addComponent(btnStop)
                            .addComponent(cboxSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin)
                    .addComponent(lblSec)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxSec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxSecActionPerformed
        // TODO add your handling code here:
        lblSec.setText("" + cboxSec.getSelectedItem());
        sec = Integer.parseInt(lblSec.getText());
    }//GEN-LAST:event_cboxSecActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
       // TODO add your handling code here:
        timer = new Timer(1000, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
            // TODO: Add your code here
            lblMin.setForeground(Color.BLACK);
            lblSec.setForeground(Color.BLACK);

            if(ifStop){
                min = min1;
                sec = sec1;
                ifStop = false;
            }

            if(sec == 0){
                sec = 60;
                min--;
            }

            if(min == 0){
                lblMin.setForeground(Color.red);
                lblSec.setForeground(Color.red);
            }
            if(min < 0){
                try {
                    Sound alarmSound = new Sound("Sound.wav");
                    alarmSound.playAudio();
                    try{
                        Thread.sleep(3000); // wait for 3 seconds     
                    }
                    catch (Exception a){
                        a.printStackTrace();
                    }
                    alarmSound.stopAudio();
                } catch (IOException | UnsupportedAudioFileException | LineUnavailableException ex) {
                    ex.printStackTrace();
                }
                JOptionPane.showMessageDialog(rootPane, "Times Up", "Stopped", 0);
                min = 0;
                sec = 0;
                timer.stop();
            } else {
                sec--;
                if(sec<0){
                    sec = 59;
                    min--;
                }
                if(min<10)
                {
                    if(sec<10)
                    {
                        lblMin.setText("0" + min);
                        lblSec.setText("0" + sec);
                    }
                    
                    else
                    {
                        lblMin.setText("0" + min);
                        lblSec.setText("" + sec);
                    }
                }
                    else
                    {
                        if(sec<10)
                        {
                            lblMin.setText("" + min);
                            lblSec.setText("0" + sec);
                        }
                        else
                        {
                            lblMin.setText("" + min);
                            lblSec.setText("" + sec);
                        }
                    }
                }
            }
        });
    timer.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        min1 = min;
        sec1 = sec;
        ifStop = true;
        timer.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void cboxMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxMinActionPerformed
        // TODO add your handling code here:
        lblMin.setText("" + cboxMin.getSelectedItem());
        min = Integer.parseInt(lblMin.getText());
    }//GEN-LAST:event_cboxMinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerSwing().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JComboBox<String> cboxMin;
    private javax.swing.JComboBox<String> cboxSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSec;
    // End of variables declaration//GEN-END:variables
}
